services:

  flights_db:
    image: mariadb:12.0.2-ubi10
    container_name: flights_db
    ports:
    - "${FLIGHTSDB_HOST_PORT}:${FLIGHTSDB_PORT}"
    environment:
      - MARIADB_DATABASE=${FLIGHTSDB_DATABASE}
      - MARIADB_USER=${FLIGHTSDB_USER}
      - MARIADB_PASSWORD=${FLIGHTSDB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${FLIGHTSDB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 20s
    networks:
      - data-network
    restart: on-failure
    volumes:
      - flightdb_data:/var/lib/mysql

  data_collector:
    build: ./data_collector
    container_name: data_collector
    ports:
      - "${DATA_COLLECTOR_HOST_PORT}:${DATA_COLLECTOR_PORT}"
    environment:
      - PYTHONUNBUFFERED=1
      - DATA_COLLECTOR_PORT=${DATA_COLLECTOR_PORT}
      - FLIGHTSDB_PORT=${FLIGHTSDB_PORT}
      - FLIGHTSDB_DATABASE=${FLIGHTSDB_DATABASE}
      - FLIGHTSDB_USER=${FLIGHTSDB_USER}
      - FLIGHTSDB_PASSWORD=${FLIGHTSDB_PASSWORD}
      - FLIGHTSDB_HOST=${FLIGHTSDB_HOST}
      - SECRETS_PATH=${SECRETS_PATH}
      - REDIST_HOST=${DATA_REDIS_HOST}
      - REDIST_PORT=${REDIS_PORT}
    secrets:
      - opensky_secrets
    depends_on:
      flights_db: 
        condition: service_healthy
      data-cache:
          condition: service_healthy
    networks:
      - data-network
      - intra-network
    restart: on-failure

  data-cache: 
    image: redis:alpine
    container_name: data-cache
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 20s
    restart: always
    networks:
      - data-network
    ports:
      - "${DATA_REDIS_HOST_PORT}:${REDIS_PORT}"

  user-db: 
    image: mariadb:12.0.2-ubi10
    container_name: user-db
    restart: always 
    environment:
      - MARIADB_ROOT_PASSWORD=${PASSWORD_ROOT_DB}
      - MARIADB_DATABASE=${NAME_DB}
      - MARIADB_USER=${USER_DB}
      - MARIADB_PASSWORD=${PASSWORD_DB}
    ports:
      - "${USER_DB_HOST_PORT}:${USER_DB_PORT}"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 20s
    networks:
      - user-network
    volumes: 
      - userdb_data:/var/lib/mysql


  user-manager:
    build: ./user_manager
    container_name: user-manager
    restart: always
    ports:
      - "${USER_MANAGER_HOST_PORT}:${USER_MANAGER_PORT}"
    environment:
      - PYTHONUNBUFFERED= 1
      - HOST_DB=${HOST_DB}
      - USER_DB=${USER_DB}
      - PASSWORD_DB=${PASSWORD_DB}
      - NAME_DB=${NAME_DB}
      - USER_DB_PORT=${USER_DB_PORT}
      - REDIST_HOST=${USER_REDIS_HOST}
      - REDIST_PORT=${REDIS_PORT}
    depends_on:
      user-db:
          condition: service_healthy
      user-cache:
          condition: service_healthy
    networks:
      - user-network
      - intra-network
  
  user-cache: 
    image: redis:alpine
    container_name: user-cache
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 20s
    restart: always
    networks:
      - user-network
    ports:
      - "${USER_REDIS_HOST_PORT}:${REDIS_PORT}"

volumes:
  flightdb_data:
  userdb_data:

networks:
  user-network:
  data-network:
  intra-network:

secrets:
  opensky_secrets:
    file: "./data_collector/credentials.json"
