services:

  flights_db:
    image: mariadb:12.0.2-ubi10
    container_name: flights_db
    ports:
    - "${FLIGHTSDB_HOST_PORT}:${FLIGHTSDB_PORT}"
    environment:
      - MARIADB_DATABASE=${FLIGHTSDB_DATABASE}
      - MARIADB_USER=${FLIGHTSDB_USER}
      - MARIADB_PASSWORD=${FLIGHTSDB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${FLIGHTSDB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 2s
    restart: on-failure
    volumes:
      - mariadb_data:/var/lib/mysql

  data_collector:
    build: ./data_collector
    container_name: data_collector
    ports:
      - "${DATA_COLLECTOR_HOST_PORT}:${DATA_COLLECTOR_PORT}"
    environment:
      - DATA_COLLECTOR_PORT=${DATA_COLLECTOR_PORT}
      - FLIGHTSDB_PORT=${FLIGHTSDB_PORT}
      - FLIGHTSDB_DATABASE=${FLIGHTSDB_DATABASE}
      - FLIGHTSDB_USER=${FLIGHTSDB_USER}
      - FLIGHTSDB_PASSWORD=${FLIGHTSDB_PASSWORD}
      - FLIGHTSDB_HOST=${FLIGHTSDB_HOST}
    depends_on:
      flights_db: 
        condition: service_healthy
    restart: on-failure

volumes:
  mariadb_data: