services:

  flights_db:
    image: mariadb:12.0.2-ubi10
    container_name: flights_db
    ports:
    - "${FLIGHTSDB_HOST_PORT}:${FLIGHTSDB_PORT}"
    environment:
      - MARIADB_DATABASE=${FLIGHTSDB_DATABASE}
      - MARIADB_USER=${FLIGHTSDB_USER}
      - MARIADB_PASSWORD=${FLIGHTSDB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${FLIGHTSDB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 20s
    networks:
      - data-network
    restart: on-failure
    volumes:
      - flightdb_data:/var/lib/mysql

  data_collector:
    build: ./data_collector
    container_name: data_collector
    ports:
      - "${DATA_COLLECTOR_HOST_PORT}:${DATA_COLLECTOR_PORT}"
    environment:
      - PYTHONUNBUFFERED=1
      - DATA_COLLECTOR_PORT=${DATA_COLLECTOR_PORT}
      - FLIGHTSDB_PORT=${FLIGHTSDB_PORT}
      - FLIGHTSDB_DATABASE=${FLIGHTSDB_DATABASE}
      - FLIGHTSDB_USER=${FLIGHTSDB_USER}
      - FLIGHTSDB_PASSWORD=${FLIGHTSDB_PASSWORD}
      - FLIGHTSDB_HOST=${FLIGHTSDB_HOST}
      - SECRETS_PATH=${SECRETS_PATH}
    secrets:
      - opensky_secrets
    depends_on:
      flights_db: 
        condition: service_healthy
    networks:
      - data-network
      - intra-network
    restart: on-failure

  user-db: 
    image: mariadb:12.0.2-ubi10
    container_name: user-db
    restart: always 
    environment:
      - MARIADB_ROOT_PASSWORD=${PASSWORD_ROOT_DB}   #rootpassword
      - MARIADB_DATABASE=${NAME_DB}        #user_db
      - MARIADB_USER=${USER_DB}            #user_service
      - MARIADB_PASSWORD=${PASSWORD_DB}       #12345
    ports:
      - "${USER_DB_HOST_PORT}:${USER_DB_PORT}"
    networks:
      - user-network
    volumes: 
      - userdb_data:/var/lib/mysql


# --- USER MANAGER (Immagine costruita da noi) ---
  user-manager:
    build: ./user_manager  # Cerca il Dockerfile qui dentro
    container_name: user-manager
    restart: always
    ports:
      - "${USER_MANAGER_HOST_PORT}:${USER_MANAGER_PORT}"  # Espone Flask (REST)
      # - "50051:50051"  Espone gRPC
    environment:
      # CONFIGURAZIONE FONDAMENTALE:
      # Qui diciamo a Python di non cercare il DB su localhost, 
      # ma all'indirizzo interno di Docker chiamato 'user-db'
      - PYTHONUNBUFFERED= 1
      - HOST_DB=${HOST_DB} #user-db
      - USER_DB=${USER_DB} #user_service
      - PASSWORD_DB=${PASSWORD_DB} #12345
      - NAME_DB=${NAME_DB} #user_db
      - REDIST_HOST=${REDIS_HOST}
    depends_on:
      - user-db  # Aspetta che il DB parta
      - redis-cache
    networks:
      - user-network
      - intra-network
  
  redis-cache: 
    image: redis:alpine
    container_name: redis-cache
    restart: always
    networks:
      - user-network
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_PORT}"

volumes:
  flightdb_data:
  userdb_data:

networks:
  user-network:
  data-network:
  intra-network:

secrets:
  opensky_secrets:
    file: "./data_collector/credentials.json"
